---

- name: archive files on appservers
  hosts: all

  tasks:
  - name: create tar.gz archive
    ansible.builtin.archive:
      path: /usr/src/dba/*
      dest: /opt/dba/games.tar.gz
      format: gz
      owner: '{{ ansible_user }}'
      group: '{{ ansible_user }}'
      force_archive: yes
    become: yes
