---

- name: create an empty file (owned by respective login user)
  hosts: appservers

  tasks:
  - name: Touch a file - to create and empty file
    ansible.builtin.file:
      path: /usr/src/nfsshare.txt 
      mode: 0777
      owner: '{{ ansible_user }}'
      group: '{{ ansible_user }}'
      state: touch
    become_method: sudo 
    become: true
